// ============================================================
// Генераторы кода — чистые функции из реальных артефактов дизайна.
// LVGL UI (из uiDesign), парсер пакета и C-struct (из packet), Arduino.
// Покрыты Vitest; используются и UI Designer, и модулями CodeGen.
// ============================================================
import type { UiW, PacketField } from "./design.ts";

// Безопасное C-имя из произвольного текста.
function cident(s: string, fallback: string): string {
  const id = s.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return id || fallback;
}
const escC = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
  .replace(/[^\x20-\x7E]/g, (ch) => "\\u" + ch.charCodeAt(0).toString(16).toUpperCase().padStart(4, "0"));

// LVGL-конструктор по типу виджета (v8 API).
const LV_CREATE: Record<string, string> = {
  Button: "lv_btn_create", Label: "lv_label_create", Slider: "lv_slider_create",
  Switch: "lv_switch_create", Arc: "lv_arc_create", Chart: "lv_chart_create",
  Gauge: "lv_meter_create", Bar: "lv_bar_create", Panel: "lv_obj_create",
  Dropdown: "lv_dropdown_create", Checkbox: "lv_checkbox_create", Roller: "lv_roller_create",
  TextArea: "lv_textarea_create", Image: "lv_img_create", NavList: "lv_list_create",
};

export interface LvglOut { c: string; h: string; }

// Генерирует ui.c/ui.h для одного экрана из реальных виджетов.
export function genLvgl(widgets: UiW[], screen = "main"): LvglOut {
  const scr = cident(screen, "main");
  const names = new Map<number, string>();
  const used = new Set<string>();
  for (const w of widgets) {
    let base = cident(`${w.type}_${w.id}`, `obj_${w.id}`);
    let n = base, k = 1;
    while (used.has(n)) n = `${base}_${k++}`;
    used.add(n); names.set(w.id, `ui_${n}`);
  }

  const c: string[] = [];
  c.push(`// ui_${scr}.c — generated by UCP UI Designer (LVGL v8)`);
  c.push(`#include "ui.h"`, "");
  c.push(`lv_obj_t *ui_${scr};`);
  for (const w of widgets) c.push(`lv_obj_t *${names.get(w.id)};`);
  c.push("", `void ui_${scr}_screen_init(void) {`);
  c.push(`    ui_${scr} = lv_obj_create(NULL);`);
  c.push(`    lv_obj_clear_flag(ui_${scr}, LV_OBJ_FLAG_SCROLLABLE);`);
  for (const w of widgets) {
    const nm = names.get(w.id)!;
    const ctor = LV_CREATE[w.type] ?? "lv_obj_create";
    c.push("", `    ${nm} = ${ctor}(ui_${scr});`);
    c.push(`    lv_obj_set_pos(${nm}, ${Math.round(w.x)}, ${Math.round(w.y)});`);
    c.push(`    lv_obj_set_size(${nm}, ${Math.round(w.w)}, ${Math.round(w.h)});`);
    if (w.type === "Label") c.push(`    lv_label_set_text(${nm}, "${escC(w.text)}");`);
    else if (w.type === "Button") {
      c.push(`    lv_obj_t *${nm}_lbl = lv_label_create(${nm});`);
      c.push(`    lv_label_set_text(${nm}_lbl, "${escC(w.text || "Button")}");`);
      c.push(`    lv_obj_center(${nm}_lbl);`);
    } else if (w.type === "Arc") {
      c.push(`    lv_arc_set_range(${nm}, 0, 100);`);
      c.push(`    lv_arc_set_value(${nm}, 60);`);
    } else if (w.type === "Checkbox") c.push(`    lv_checkbox_set_text(${nm}, "${escC(w.text || "Check")}");`);
    else if (w.type === "TextArea") c.push(`    lv_textarea_set_text(${nm}, "${escC(w.text)}");`);
    else if (w.type === "Dropdown" || w.type === "Roller")
      c.push(`    ${w.type === "Dropdown" ? "lv_dropdown_set_options" : "lv_roller_set_options"}(${nm}, "${escC(w.text || "A\\nB\\nC")}"${w.type === "Roller" ? ", LV_ROLLER_MODE_NORMAL" : ""});`);
  }
  c.push("}", "");

  const h: string[] = [];
  h.push(`// ui.h — generated by UCP UI Designer`);
  h.push("#ifndef UI_H", "#define UI_H", "", "#include \"lvgl.h\"", "");
  h.push(`extern lv_obj_t *ui_${scr};`);
  for (const w of widgets) h.push(`extern lv_obj_t *${names.get(w.id)};`);
  h.push("", `void ui_${scr}_screen_init(void);`, "", "#endif // UI_H", "");
  return { c: c.join("\n"), h: h.join("\n") };
}

// --- Packet → C struct (#pragma pack) ---
const ctypeOf = (bytes: number) => bytes === 1 ? "uint8_t" : bytes === 2 ? "uint16_t" : "uint32_t";

export function genPacketStruct(fields: PacketField[], name = "frame"): string {
  const out: string[] = [`// ${name}_t — generated by UCP Packet Editor`, "#include <stdint.h>", "",
    "#pragma pack(push, 1)", "typedef struct {"];
  const seen = new Set<string>();
  fields.forEach((f, i) => {
    let nm = cident(f.name, `f${i}`);
    while (seen.has(nm)) nm = `${nm}_`;
    seen.add(nm);
    out.push(`    ${ctypeOf(f.bytes)} ${nm};`);
  });
  out.push(`} ${name}_t;`, "#pragma pack(pop)", "");
  return out.join("\n");
}

// --- Packet → парсер (C / Python), big-endian, CRC если есть поле crc ---
export function genProtoParser(fields: PacketField[], lang: "c" | "py", name = "frame"): string {
  const total = fields.reduce((s, f) => s + f.bytes, 0);
  const header = fields[0];
  const hdrVal = header ? header.value & ((1 << (header.bytes * 8)) - 1) : 0;
  const hasCrc = fields.some((f) => /crc/i.test(f.name));
  const crcIdx = fields.findIndex((x) => /crc/i.test(x.name));
  const crcLen = fields.filter((_, i) => i < crcIdx).reduce((s, f) => s + f.bytes, 0);
  const names = new Set<string>();
  const fname = (f: PacketField, i: number) => { let n = cident(f.name, `f${i}`); while (names.has(n)) n = `${n}_`; names.add(n); return n; };

  if (lang === "c") {
    const out: string[] = [`// ${name}_parse.c — generated by UCP Protocol Code Gen`, "#include <stdint.h>", "#include <stdbool.h>", "#include <stddef.h>", ""];
    out.push("typedef struct {");
    const fn: string[] = [];
    fields.forEach((f, i) => { const n = fname(f, i); fn.push(n); out.push(`    ${ctypeOf(f.bytes)} ${n};`); });
    out.push(`} ${name}_t;`, "");
    out.push(`bool ${name}_parse(const uint8_t *buf, size_t n, ${name}_t *out) {`);
    out.push(`    if (n < ${total}${header ? ` || buf[0] != 0x${hdrVal.toString(16).toUpperCase()}` : ""}) return false;`);
    let off = 0;
    fields.forEach((f, i) => {
      const expr = f.bytes === 1 ? `buf[${off}]`
        : Array.from({ length: f.bytes }, (_, k) => `((uint32_t)buf[${off + k}] << ${(f.bytes - 1 - k) * 8})`).join(" | ");
      out.push(`    out->${fn[i]} = ${expr};`);
      off += f.bytes;
    });
    if (hasCrc) out.push(`    return crc16_ccitt(buf, ${crcLen}) == out->crc;`);
    else out.push("    return true;");
    out.push("}");
    return out.join("\n");
  }
  // Python
  const fmt = ">" + fields.map((f) => f.bytes === 1 ? "B" : f.bytes === 2 ? "H" : "I").join("");
  const fieldNames = fields.map((f, i) => fname(f, i));
  const out: string[] = [`# ${name}_parse.py — generated by UCP Protocol Code Gen`, "import struct", "",
    `def ${name}_parse(buf: bytes):`,
    `    if len(buf) < ${total}${header ? ` or buf[0] != 0x${hdrVal.toString(16).toUpperCase()}` : ""}:`,
    "        return None",
    `    ${fieldNames.join(", ")}${fieldNames.length === 1 ? "," : ""} = struct.unpack("${fmt}", buf[:${total}])`];
  if (hasCrc) out.push(`    if crc16_ccitt(buf[:${crcLen}]) != crc:`, "        return None");
  out.push(`    return dict(${fieldNames.map((n) => `${n}=${n}`).join(", ")})`);
  return out.join("\n");
}

// --- Arduino / ESP-IDF blink (параметрический) ---
export interface BlinkOpts { pin: number; baud: number; delayMs: number; target: "arduino" | "espidf"; }
export function genBlink(o: BlinkOpts): string {
  if (o.target === "arduino") {
    return `// sketch.ino — generated by UCP
#include <Arduino.h>
#define LED_PIN  ${o.pin}
#define BAUD     ${o.baud}

void setup() {
  Serial.begin(BAUD);
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(${o.delayMs});
  digitalWrite(LED_PIN, LOW);
  delay(${o.delayMs});
}`;
  }
  return `// main.c — generated by UCP (ESP-IDF)
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#define LED_PIN  ${o.pin}

void app_main(void) {
  gpio_set_direction(LED_PIN, GPIO_MODE_OUTPUT);
  while (1) {
    gpio_set_level(LED_PIN, 1);
    vTaskDelay(pdMS_TO_TICKS(${o.delayMs}));
    gpio_set_level(LED_PIN, 0);
    vTaskDelay(pdMS_TO_TICKS(${o.delayMs}));
  }
}`;
}
