import { describe, it, expect } from "vitest";
import { genLvgl, genLvglProject, genLvglImageAsset, genLvglReadme, genPacketStruct, genProtoParser, genBlink, genFsm, genRegisterHeader, genRegisterMarkdown } from "./codegen.ts";
import type { UiW, PacketField, FsmDesign, RegisterMapDesign } from "./design.ts";

const widgets: UiW[] = [
  { id: 1, type: "Label", x: 10, y: 20, w: 100, h: 28, text: "Hi 60°C" },
  { id: 2, type: "Button", x: 5, y: 60, w: 120, h: 40, text: "GO" },
];
const fields: PacketField[] = [
  { id: 1, name: "header", bytes: 1, value: 0xAA },
  { id: 2, name: "cmd", bytes: 1, value: 0x03 },
  { id: 3, name: "length", bytes: 2, value: 4 },
  { id: 4, name: "crc", bytes: 2, value: 0x1A3F },
];

describe("genLvgl", () => {
  const { c, h } = genLvgl(widgets, "main");
  it("создаёт виджеты реальных типов", () => {
    expect(c).toContain("lv_label_create(ui_main)");
    expect(c).toContain("lv_btn_create(ui_main)");
    expect(c).toContain("ui_main_screen_init(void)");
  });
  it("экранирует не-ASCII в строке Label", () => {
    expect(c).toContain('lv_label_set_text(ui_Label_1, "Hi 60\\u00B0C")');
  });
  it("заголовок с extern и прототипом", () => {
    expect(h).toContain("extern lv_obj_t *ui_main;");
    expect(h).toContain("void ui_main_screen_init(void);");
  });
  it("golden output фиксирует текущий LVGL v8 single-screen baseline", () => {
    expect(c).toBe([
      "// ui_main.c — generated by UCP UI Designer (LVGL v8)",
      "#include \"ui.h\"",
      "",
      "lv_obj_t *ui_main;",
      "lv_obj_t *ui_Label_1;",
      "lv_obj_t *ui_Button_2;",
      "",
      "void ui_main_screen_init(void) {",
      "    ui_main = lv_obj_create(NULL);",
      "    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);",
      "",
      "    ui_Label_1 = lv_label_create(ui_main);",
      "    lv_obj_set_pos(ui_Label_1, 10, 20);",
      "    lv_obj_set_size(ui_Label_1, 100, 28);",
      "    lv_label_set_text(ui_Label_1, \"Hi 60\\u00B0C\");",
      "",
      "    ui_Button_2 = lv_btn_create(ui_main);",
      "    lv_obj_set_pos(ui_Button_2, 5, 60);",
      "    lv_obj_set_size(ui_Button_2, 120, 40);",
      "    lv_obj_t *ui_Button_2_lbl = lv_label_create(ui_Button_2);",
      "    lv_label_set_text(ui_Button_2_lbl, \"GO\");",
      "    lv_obj_center(ui_Button_2_lbl);",
      "}",
      "",
    ].join("\n"));
    expect(h).toBe([
      "// ui.h — generated by UCP UI Designer",
      "#ifndef UI_H",
      "#define UI_H",
      "",
      "#include \"lvgl.h\"",
      "",
      "extern lv_obj_t *ui_main;",
      "extern lv_obj_t *ui_Label_1;",
      "extern lv_obj_t *ui_Button_2;",
      "",
      "void ui_main_screen_init(void);",
      "",
      "#endif // UI_H",
      "",
    ].join("\n"));
  });

  it("generates LVGL event callback stub and registration", () => {
    const out = genLvgl([
      { id: 1, type: "Button", x: 10, y: 20, w: 100, h: 40, text: "Start", event: { code: "clicked", handler: "on_start_clicked" } },
    ], "main");
    expect(out.c).toContain("static void on_start_clicked(lv_event_t *e) {");
    expect(out.c).toContain("    (void)e;");
    expect(out.c).toContain("    /* TODO: user action */");
    expect(out.c).toContain("lv_obj_add_event_cb(ui_Button_1, on_start_clicked, LV_EVENT_CLICKED, NULL);");
  });

  it("generates LVGL style token init and attachment", () => {
    const out = genLvgl([
      { id: 1, type: "Button", x: 10, y: 20, w: 100, h: 40, text: "Start", style: { bgColor: "#1f6feb", radius: 8 } },
    ], "main");
    expect(out.c).toContain("static lv_style_t ui_Button_1_style;");
    expect(out.c).toContain("lv_style_init(&ui_Button_1_style);");
    expect(out.c).toContain("lv_style_set_bg_color(&ui_Button_1_style, lv_color_hex(0x1F6FEB));");
    expect(out.c).toContain("lv_style_set_bg_opa(&ui_Button_1_style, LV_OPA_COVER);");
    expect(out.c).toContain("lv_style_set_radius(&ui_Button_1_style, 8);");
    expect(out.c).toContain("lv_obj_add_style(ui_Button_1, &ui_Button_1_style, LV_PART_MAIN | LV_STATE_DEFAULT);");
  });

  it("emits extended style tokens (text, border, padding) only when set", () => {
    const out = genLvgl([
      { id: 1, type: "Label", x: 0, y: 0, w: 100, h: 28, text: "Hi", style: { textColor: "#ff8800", textAlign: "center", borderWidth: 2, borderColor: "#101820", pad: 6 } },
    ], "main");
    expect(out.c).toContain("lv_style_set_text_color(&ui_Label_1_style, lv_color_hex(0xFF8800));");
    expect(out.c).toContain("lv_style_set_text_align(&ui_Label_1_style, LV_TEXT_ALIGN_CENTER);");
    expect(out.c).toContain("lv_style_set_border_width(&ui_Label_1_style, 2);");
    expect(out.c).toContain("lv_style_set_border_color(&ui_Label_1_style, lv_color_hex(0x101820));");
    expect(out.c).toContain("lv_style_set_pad_all(&ui_Label_1_style, 6);");
    // bg/radius not set -> not emitted for this widget
    expect(out.c).not.toContain("lv_style_set_bg_color(&ui_Label_1_style");
    expect(out.c).not.toContain("lv_style_set_radius(&ui_Label_1_style");
  });

  it("emits a built-in Montserrat font when set", () => {
    const out = genLvgl([
      { id: 1, type: "Label", x: 0, y: 0, w: 100, h: 28, text: "Hi", style: { font: 24 } },
    ], "main");
    expect(out.c).toContain("lv_style_set_text_font(&ui_Label_1_style, &lv_font_montserrat_24);");
    const none = genLvgl([{ id: 2, type: "Label", x: 0, y: 0, w: 100, h: 28, text: "Hi", style: { radius: 4 } }], "main");
    expect(none.c).not.toContain("lv_style_set_text_font");
  });

  it("emits a pressed-state style as a separate lv_style_t", () => {
    const out = genLvgl([
      { id: 1, type: "Button", x: 0, y: 0, w: 80, h: 30, text: "X", style: { bgColor: "#1f6feb", pressedBgColor: "#0a3d91" } },
    ], "main");
    expect(out.c).toContain("static lv_style_t ui_Button_1_style_pressed;");
    expect(out.c).toContain("lv_style_set_bg_color(&ui_Button_1_style_pressed, lv_color_hex(0x0A3D91));");
    expect(out.c).toContain("lv_obj_add_style(ui_Button_1, &ui_Button_1_style_pressed, LV_PART_MAIN | LV_STATE_PRESSED);");
    // default style still emitted
    expect(out.c).toContain("lv_obj_add_style(ui_Button_1, &ui_Button_1_style, LV_PART_MAIN | LV_STATE_DEFAULT);");
  });

  it("emits a pressed-only widget's pressed style without a default style", () => {
    const out = genLvgl([
      { id: 1, type: "Button", x: 0, y: 0, w: 80, h: 30, text: "X", style: { pressedBgColor: "#0a3d91" } },
    ], "main");
    expect(out.c).toContain("static lv_style_t ui_Button_1_style_pressed;");
    expect(out.c).toContain("lv_obj_add_style(ui_Button_1, &ui_Button_1_style_pressed, LV_PART_MAIN | LV_STATE_PRESSED);");
    expect(out.c).not.toContain("static lv_style_t ui_Button_1_style;");
    expect(out.c).not.toContain("LV_STATE_DEFAULT");
  });

  it("leaves a token-free widget without any lv_style call", () => {
    const out = genLvgl([{ id: 1, type: "Label", x: 0, y: 0, w: 100, h: 28, text: "Hi" }], "main");
    expect(out.c).not.toContain("lv_style_");
  });

  it("generates LVGL image asset declarations and explicit missing-asset TODOs", () => {
    const withAsset = genLvgl([
      { id: 1, type: "Image", x: 12, y: 16, w: 64, h: 64, text: "", assetId: "img_logo" },
    ], "main");
    expect(withAsset.c).toContain("LV_IMG_DECLARE(img_logo);");
    expect(withAsset.c).toContain("lv_img_set_src(ui_Image_1, &img_logo);");

    const missing = genLvgl([
      { id: 2, type: "Image", x: 12, y: 16, w: 64, h: 64, text: "" },
    ], "main");
    expect(missing.c).toContain("/* TODO: assign assetId to emit lv_img_set_src(ui_Image_2, &asset); */");
  });

  it("generates LVGL flex layout for Panel containers", () => {
    const out = genLvgl([
      { id: 1, type: "Panel", x: 0, y: 0, w: 200, h: 80, text: "", layout: { kind: "flex_column", gap: 6 } },
    ], "main");
    expect(out.c).toContain("lv_obj_set_layout(ui_Panel_1, LV_LAYOUT_FLEX);");
    expect(out.c).toContain("lv_obj_set_flex_flow(ui_Panel_1, LV_FLEX_FLOW_COLUMN);");
    expect(out.c).toContain("lv_obj_set_style_pad_row(ui_Panel_1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);");
    expect(out.c).toContain("lv_obj_set_style_pad_column(ui_Panel_1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);");
    expect(out.c).not.toContain("lv_obj_set_flex_align");
  });

  it("emits main-axis flex align only when the layout sets it", () => {
    const out = genLvgl([
      { id: 1, type: "Panel", x: 0, y: 0, w: 200, h: 80, text: "", layout: { kind: "flex_row", gap: 4, align: "space_between" } },
    ], "main");
    expect(out.c).toContain("lv_obj_set_flex_align(ui_Panel_1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);");
  });

  it("fills cross-axis flex align without a main-axis value", () => {
    const out = genLvgl([
      { id: 1, type: "Panel", x: 0, y: 0, w: 200, h: 80, text: "", layout: { kind: "flex_row", crossAlign: "center" } },
    ], "main");
    expect(out.c).toContain("lv_obj_set_flex_align(ui_Panel_1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);");
  });

  it("fills all three flex align arguments", () => {
    const out = genLvgl([
      { id: 1, type: "Panel", x: 0, y: 0, w: 200, h: 80, text: "", layout: { kind: "flex_row", align: "center", crossAlign: "end", trackAlign: "space_evenly" } },
    ], "main");
    expect(out.c).toContain("lv_obj_set_flex_align(ui_Panel_1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_SPACE_EVENLY);");
  });

  it("emits hidden flag and opacity only when set", () => {
    const out = genLvgl([
      { id: 1, type: "Button", x: 0, y: 0, w: 80, h: 30, text: "X", hidden: true, opa: 128 },
      { id: 2, type: "Label", x: 0, y: 40, w: 80, h: 20, text: "Y" },
    ], "main");
    expect(out.c).toContain("lv_obj_add_flag(ui_Button_1, LV_OBJ_FLAG_HIDDEN);");
    expect(out.c).toContain("lv_obj_set_style_opa(ui_Button_1, 128, LV_PART_MAIN | LV_STATE_DEFAULT);");
    expect(out.c).not.toContain("lv_obj_add_flag(ui_Label_2");
    expect(out.c).not.toContain("lv_obj_set_style_opa(ui_Label_2");
  });

  it("emits per-child flex grow only when set", () => {
    const grown = genLvgl([
      { id: 1, type: "Panel", x: 0, y: 0, w: 200, h: 80, text: "", layout: { kind: "flex_row" } },
      { id: 2, type: "Label", x: 0, y: 0, w: 40, h: 20, text: "Hi", parentId: 1, flexGrow: 2 },
    ], "main");
    expect(grown.c).toContain("lv_obj_set_flex_grow(ui_Label_2, 2);");

    const plain = genLvgl([
      { id: 1, type: "Panel", x: 0, y: 0, w: 200, h: 80, text: "", layout: { kind: "flex_row" } },
      { id: 2, type: "Label", x: 0, y: 0, w: 40, h: 20, text: "Hi", parentId: 1 },
    ], "main");
    expect(plain.c).not.toContain("lv_obj_set_flex_grow");
  });

  it("creates child widgets under Panel parents", () => {
    const out = genLvgl([
      { id: 2, type: "Label", x: 8, y: 10, w: 100, h: 24, text: "Child", parentId: 1 },
      { id: 1, type: "Panel", x: 0, y: 0, w: 200, h: 80, text: "" },
    ], "main");
    expect(out.c).toContain("ui_Panel_1 = lv_obj_create(ui_main);");
    expect(out.c).toContain("ui_Label_2 = lv_label_create(ui_Panel_1);");
    expect(out.c.indexOf("ui_Panel_1 = lv_obj_create(ui_main);")).toBeLessThan(out.c.indexOf("ui_Label_2 = lv_label_create(ui_Panel_1);"));
  });
});

describe("genLvglProject", () => {
  it("generates exact multi-screen LVGL v8 baseline with scoped names", () => {
    const { c, h } = genLvglProject({
      initialScreenId: "main",
      screens: [
        {
          id: "main",
          widgets: [
            { id: 1, type: "Label", x: 8, y: 12, w: 96, h: 24, text: "Main" },
          ],
        },
        {
          id: "settings",
          widgets: [
            { id: 1, type: "Button", x: 20, y: 240, w: 120, h: 38, text: "Back" },
          ],
        },
      ],
    });
    expect(c).toBe([
      "// ui.c — generated by UCP UI Designer (LVGL v8 multi-screen)",
      "#include \"ui.h\"",
      "",
      "lv_obj_t *ui_main;",
      "lv_obj_t *ui_main_Label_1;",
      "lv_obj_t *ui_settings;",
      "lv_obj_t *ui_settings_Button_1;",
      "",
      "void ui_main_screen_init(void) {",
      "    ui_main = lv_obj_create(NULL);",
      "    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);",
      "",
      "    ui_main_Label_1 = lv_label_create(ui_main);",
      "    lv_obj_set_pos(ui_main_Label_1, 8, 12);",
      "    lv_obj_set_size(ui_main_Label_1, 96, 24);",
      "    lv_label_set_text(ui_main_Label_1, \"Main\");",
      "}",
      "",
      "void ui_settings_screen_init(void) {",
      "    ui_settings = lv_obj_create(NULL);",
      "    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);",
      "",
      "    ui_settings_Button_1 = lv_btn_create(ui_settings);",
      "    lv_obj_set_pos(ui_settings_Button_1, 20, 240);",
      "    lv_obj_set_size(ui_settings_Button_1, 120, 38);",
      "    lv_obj_t *ui_settings_Button_1_lbl = lv_label_create(ui_settings_Button_1);",
      "    lv_label_set_text(ui_settings_Button_1_lbl, \"Back\");",
      "    lv_obj_center(ui_settings_Button_1_lbl);",
      "}",
      "",
      "void ui_init(void) {",
      "    ui_main_screen_init();",
      "    ui_settings_screen_init();",
      "    lv_scr_load(ui_main);",
      "}",
      "",
    ].join("\n"));
    expect(h).toBe([
      "// ui.h — generated by UCP UI Designer",
      "#ifndef UI_H",
      "#define UI_H",
      "",
      "#include \"lvgl.h\"",
      "",
      "extern lv_obj_t *ui_main;",
      "extern lv_obj_t *ui_main_Label_1;",
      "extern lv_obj_t *ui_settings;",
      "extern lv_obj_t *ui_settings_Button_1;",
      "",
      "void ui_main_screen_init(void);",
      "void ui_settings_screen_init(void);",
      "void ui_init(void);",
      "",
      "#endif // UI_H",
      "",
    ].join("\n"));
  });

  it("generates project-level event handlers across screens", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      screens: [
        { id: "main", widgets: [{ id: 1, type: "Label", x: 0, y: 0, w: 80, h: 20, text: "Main" }] },
        { id: "settings", widgets: [{ id: 2, type: "Slider", x: 8, y: 48, w: 160, h: 20, text: "", event: { code: "value_changed", handler: "on_speed_changed" } }] },
      ],
    });
    expect(c).toContain("static void on_speed_changed(lv_event_t *e) {");
    expect(c).toContain("lv_obj_add_event_cb(ui_settings_Slider_2, on_speed_changed, LV_EVENT_VALUE_CHANGED, NULL);");
  });

  it("generates project-level screen-load event actions", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      screens: [
        {
          id: "main",
          widgets: [
            {
              id: 1,
              type: "Button",
              x: 12,
              y: 220,
              w: 120,
              h: 36,
              text: "Settings",
              event: { code: "clicked", handler: "open_settings", action: { kind: "screen_load", targetScreenId: "settings" } },
            },
          ],
        },
        { id: "settings", widgets: [{ id: 1, type: "Label", x: 8, y: 12, w: 96, h: 24, text: "Settings" }] },
      ],
    });
    expect(c).toContain("static void open_settings(lv_event_t *e) {");
    expect(c).toContain("    lv_scr_load(ui_settings);");
    expect(c).toContain("lv_obj_add_event_cb(ui_main_Button_1, open_settings, LV_EVENT_CLICKED, NULL);");
  });

  it("generates project-level style declarations with screen-scoped names", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      screens: [
        { id: "main", widgets: [{ id: 1, type: "Label", x: 0, y: 0, w: 80, h: 20, text: "Main" }] },
        { id: "settings", widgets: [{ id: 2, type: "Button", x: 8, y: 48, w: 120, h: 36, text: "Apply", style: { bgColor: "#2ea043", radius: 6 } }] },
      ],
    });
    expect(c).toContain("static lv_style_t ui_settings_Button_2_style;");
    expect(c).toContain("lv_style_set_bg_color(&ui_settings_Button_2_style, lv_color_hex(0x2EA043));");
    expect(c).toContain("lv_obj_add_style(ui_settings_Button_2, &ui_settings_Button_2_style, LV_PART_MAIN | LV_STATE_DEFAULT);");
  });

  it("genLvglReadme lists screens and declared assets", () => {
    const readme = genLvglReadme({
      initialScreenId: "main",
      assets: [{ id: "img_logo", src: "assets/logo.png" }, { id: "img_px", w: 2, h: 1, format: "rgb565", data: [1, 2, 3, 4] }],
      screens: [
        { id: "main", widgets: [{ id: 1, type: "Label", x: 0, y: 0, w: 10, h: 10, text: "Hi" }] },
        { id: "settings", widgets: [] },
      ],
    });
    expect(readme).toContain("Screens (2):");
    expect(readme).toContain("- main (1 widgets)");
    expect(readme).toContain("img_logo: extern, src: assets/logo.png");
    expect(readme).toContain("img_px: inline rgb565 2x1");
    expect(readme).toContain("ui_init();");
  });

  it("renames symbols in v9 mode (verified v8->v9 deltas)", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      assets: [{ id: "img_px", w: 2, h: 1, format: "rgb565a8", data: [0, 0, 0, 0, 0, 0] }],
      screens: [
        {
          id: "main",
          widgets: [
            { id: 1, type: "Button", x: 0, y: 0, w: 80, h: 30, text: "Go", event: { code: "clicked", handler: "on_go", action: { kind: "screen_load", targetScreenId: "settings" } } },
            { id: 2, type: "Image", x: 0, y: 40, w: 32, h: 32, text: "", assetId: "img_px" },
            { id: 3, type: "Gauge", x: 0, y: 80, w: 40, h: 40, text: "" },
          ],
        },
        { id: "settings", widgets: [] },
      ],
    }, "v9");
    expect(c).toContain("(LVGL v9 multi-screen)");
    expect(c).toContain("lv_button_create(ui_main)");
    expect(c).toContain("lv_image_create(ui_main)");
    expect(c).toContain("lv_scale_create(ui_main)");
    expect(c).toContain("lv_image_set_src(ui_main_Image_2, &img_px);");
    expect(c).toContain("const lv_image_dsc_t img_px = {");
    expect(c).toContain(".header.cf = LV_COLOR_FORMAT_RGB565A8,");
    expect(c).toContain("lv_obj_remove_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);");
    expect(c).toContain("lv_obj_add_event(ui_main_Button_1, on_go, LV_EVENT_CLICKED, NULL);");
    expect(c).toContain("lv_screen_load(ui_settings);");
    // no v8 names leaked
    expect(c).not.toContain("lv_btn_create");
    expect(c).not.toContain("lv_img_create");
    expect(c).not.toContain("lv_scr_load");
    expect(c).not.toContain("LV_IMG_CF_");
  });

  it("v8 mode is the default and keeps v8 names", () => {
    const { c } = genLvglProject({ initialScreenId: "main", screens: [{ id: "main", widgets: [{ id: 1, type: "Button", x: 0, y: 0, w: 80, h: 30, text: "Go" }] }] });
    expect(c).toContain("lv_btn_create(ui_main)");
    expect(c).toContain("lv_scr_load(ui_main);");
    expect(c).not.toContain("lv_button_create");
  });

  it("genLvglImageAsset uses v9 descriptor names in v9 mode", () => {
    const dsc = genLvglImageAsset({ id: "img_a", w: 1, h: 1, format: "rgb565", data: [0x1F, 0x00] }, "v9");
    expect(dsc).toContain("const lv_image_dsc_t img_a = {");
    expect(dsc).toContain(".header.cf = LV_COLOR_FORMAT_RGB565,");
  });

  it("deduplicates project-level image asset declarations across screens", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      screens: [
        { id: "main", widgets: [{ id: 1, type: "Image", x: 4, y: 4, w: 32, h: 32, text: "", assetId: "img_logo" }] },
        { id: "settings", widgets: [{ id: 1, type: "Image", x: 8, y: 8, w: 32, h: 32, text: "", assetId: "img_logo" }] },
      ],
    });
    expect(c.match(/LV_IMG_DECLARE\(img_logo\);/g)).toHaveLength(1);
    expect(c).toContain("lv_img_set_src(ui_main_Image_1, &img_logo);");
    expect(c).toContain("lv_img_set_src(ui_settings_Image_1, &img_logo);");
  });

  it("comments declared asset sources from the project manifest", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      assets: [{ id: "img_logo", src: "assets/logo.png" }, { id: "img_unused" }],
      screens: [
        { id: "main", widgets: [{ id: 1, type: "Image", x: 4, y: 4, w: 32, h: 32, text: "", assetId: "img_logo" }] },
      ],
    });
    expect(c).toContain("LV_IMG_DECLARE(img_logo); // src: assets/logo.png");
    expect(c).toContain("LV_IMG_DECLARE(img_unused);");
    expect(c.match(/LV_IMG_DECLARE\(img_logo\)/g)).toHaveLength(1);
    expect(c).not.toContain('not declared in the project asset manifest');
  });

  it("emits an inline LVGL image descriptor for manifest assets with pixel data", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      assets: [{ id: "img_px", w: 2, h: 1, format: "rgb565", data: [0x1F, 0x00, 0x00, 0xF8] }],
      screens: [
        { id: "main", widgets: [{ id: 1, type: "Image", x: 0, y: 0, w: 2, h: 1, text: "", assetId: "img_px" }] },
      ],
    });
    expect(c).toContain("static const uint8_t img_px_map[] = {");
    expect(c).toContain("0x1F, 0x00, 0x00, 0xF8,");
    expect(c).toContain("const lv_img_dsc_t img_px = {");
    expect(c).toContain(".header.cf = LV_IMG_CF_TRUE_COLOR,");
    expect(c).toContain(".header.w = 2,");
    expect(c).toContain(".data_size = 4,");
    expect(c).toContain(".data = img_px_map,");
    expect(c).toContain("lv_img_set_src(ui_main_Image_1, &img_px);");
    expect(c).not.toContain("LV_IMG_DECLARE(img_px)");
  });

  it("genLvglImageAsset returns null without valid pixel data", () => {
    expect(genLvglImageAsset({ id: "img_logo", src: "assets/logo.png" })).toBeNull();
    expect(genLvglImageAsset({ id: "img_bad", w: 2, h: 1, format: "rgb565", data: [1, 2] })).toBeNull();
  });

  it("emits TRUE_COLOR_ALPHA descriptor for an rgb565a8 asset", () => {
    const dsc = genLvglImageAsset({ id: "img_a", w: 2, h: 1, format: "rgb565a8", data: [0x00, 0xF8, 0x80, 0x1F, 0x00, 0xFF] });
    expect(dsc).toContain(".header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,");
    expect(dsc).toContain(".data_size = 6,");
    expect(dsc).toContain("0x00, 0xF8, 0x80, 0x1F, 0x00, 0xFF,");
  });

  it("warns about widget assets missing from a non-empty manifest", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      assets: [{ id: "img_logo", src: "assets/logo.png" }],
      screens: [
        { id: "main", widgets: [{ id: 1, type: "Image", x: 4, y: 4, w: 32, h: 32, text: "", assetId: "img_logo" }] },
        { id: "settings", widgets: [{ id: 2, type: "Image", x: 8, y: 8, w: 32, h: 32, text: "", assetId: "img_extra" }] },
      ],
    });
    expect(c).toContain("LV_IMG_DECLARE(img_extra);");
    expect(c).toContain('/* TODO: image asset "img_extra" is used but not declared in the project asset manifest */');
    expect(c).not.toContain('"img_logo" is used but not declared');
  });

  it("generates screen-scoped Panel flex layout", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      screens: [
        { id: "main", widgets: [] },
        { id: "settings", widgets: [{ id: 2, type: "Panel", x: 8, y: 8, w: 160, h: 64, text: "", layout: { kind: "flex_row", gap: 4 } }] },
      ],
    });
    expect(c).toContain("lv_obj_set_layout(ui_settings_Panel_2, LV_LAYOUT_FLEX);");
    expect(c).toContain("lv_obj_set_flex_flow(ui_settings_Panel_2, LV_FLEX_FLOW_ROW);");
    expect(c).toContain("lv_obj_set_style_pad_row(ui_settings_Panel_2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);");
  });

  it("creates screen-scoped child widgets under Panel parents", () => {
    const { c } = genLvglProject({
      initialScreenId: "main",
      screens: [
        { id: "main", widgets: [] },
        {
          id: "settings",
          widgets: [
            { id: 2, type: "Panel", x: 8, y: 8, w: 160, h: 64, text: "" },
            { id: 3, type: "Label", x: 6, y: 6, w: 80, h: 20, text: "Inside", parentId: 2 },
          ],
        },
      ],
    });
    expect(c).toContain("ui_settings_Label_3 = lv_label_create(ui_settings_Panel_2);");
  });
});

describe("genPacketStruct", () => {
  it("упакованная структура с верными типами", () => {
    const s = genPacketStruct(fields);
    expect(s).toContain("#pragma pack(push, 1)");
    expect(s).toContain("uint8_t header;");
    expect(s).toContain("uint16_t length;");
    expect(s).toContain("} frame_t;");
  });
});

describe("genProtoParser", () => {
  it("C: проверка заголовка, big-endian, CRC", () => {
    const c = genProtoParser(fields, "c");
    expect(c).toContain("buf[0] != 0xAA");
    expect(c).toContain("out->length = ((uint32_t)buf[2] << 8) | ((uint32_t)buf[3] << 0);");
    expect(c).toContain("crc16_ccitt(buf, 4) == out->crc");
  });
  it("Python: struct.unpack с верным форматом", () => {
    const py = genProtoParser(fields, "py");
    expect(py).toContain('struct.unpack(">BBHH", buf[:6])');
    expect(py).toContain("header, cmd, length, crc = ");
  });
});

describe("genBlink", () => {
  it("параметры подставляются", () => {
    expect(genBlink({ pin: 13, baud: 9600, delayMs: 250, target: "arduino" })).toContain("#define LED_PIN  13");
    expect(genBlink({ pin: 2, baud: 115200, delayMs: 100, target: "espidf" })).toContain("pdMS_TO_TICKS(100)");
  });
});

describe("genFsm", () => {
  const fsm: FsmDesign = {
    name: "Dryer",
    initial: "idle",
    states: [
      { id: "idle", name: "IDLE", x: 0, y: 0 },
      { id: "heat", name: "HEAT", x: 0, y: 0 },
      { id: "fault", name: "FAULT", x: 0, y: 0 },
    ],
    transitions: [
      { from: "idle", to: "heat", event: "START" },
      { from: "heat", to: "idle", event: "TIMEOUT", guard: "elapsed_ms > dry_ms", action: "heater_off();" },
      { from: "heat", to: "fault", event: "FAULT", action: "fault_latch();" },
    ],
  };
  const out = genFsm(fsm);

  it("generates state and event enums", () => {
    expect(out.h).toContain("ST_IDLE");
    expect(out.h).toContain("ST_HEAT");
    expect(out.h).toContain("ST_FAULT");
    expect(out.h).toContain("EV_START");
    expect(out.h).toContain("EV_TIMEOUT");
    expect(out.c).toContain("case ST_HEAT:");
  });

  it("puts guard and action into transition body", () => {
    expect(out.c).toContain("if (ev == EV_TIMEOUT && (elapsed_ms > dry_ms))");
    expect(out.c).toContain("heater_off();");
    expect(out.c).toContain("return ST_IDLE;");
  });

  it("defines initial state", () => {
    expect(out.h).toContain("#define FSM_INITIAL ST_IDLE");
  });
});

describe("genRegisterMap", () => {
  const map: RegisterMapDesign = {
    device: "SENSOR",
    base: 0x40001000,
    registers: [
      {
        id: 1,
        name: "CFG",
        addr: 0x10,
        access: "rw",
        reset: 0,
        desc: "Configuration",
        fields: [
          { id: 1, name: "EN", lsb: 0, width: 1 },
          { id: 2, name: "MODE", lsb: 4, width: 2 },
        ],
      },
    ],
  };

  it("generates C address, masks and inline helpers", () => {
    const h = genRegisterHeader(map);
    expect(h).toContain("#define SENSOR_BASE 0x40001000");
    expect(h).toContain("#define SENSOR_CFG_ADDR (SENSOR_BASE + SENSOR_CFG_OFFSET)");
    expect(h).toContain("#define SENSOR_CFG_MODE_Msk (0x3 << 4)");
    expect(h).toContain("SENSOR_CFG_MODE_GET");
    expect(h).toContain("SENSOR_CFG_MODE_SET");
  });

  it("generates markdown register and field tables", () => {
    const md = genRegisterMarkdown(map);
    expect(md).toContain("# SENSOR Register Map");
    expect(md).toContain("| CFG | `0x10` | RW | `0x00000000` | Configuration |");
    expect(md).toContain("| MODE | 5:4 |");
  });
});
