import { useState } from "react";
import { useUcp } from "../store.ts";
import { MODULE_INDEX, type ModuleDef } from "../data/modules.ts";
import { PanelHead } from "./common.tsx";

function CodeShell({ mod, code, controls }: { mod: ModuleDef; code: string; controls?: React.ReactNode }) {
  const ucp = useUcp();
  return (
    <div>
      <PanelHead mod={mod} right={<button className="btn primary" onClick={() => { navigator.clipboard?.writeText(code); ucp.setStatus(`Copied ${mod.title} output`); }}>Copy</button>} />
      {controls && <div className="card toolbar" style={{ marginBottom: 12 }}>{controls}</div>}
      <div className="card" style={{ padding: 0 }}>
        <pre className="code" style={{ border: "none", maxHeight: 420, margin: 0 }}>{code}</pre>
      </div>
    </div>
  );
}

export function LvglExportView() {
  const [screen, setScreen] = useState("main");
  const code =
`// ui_${screen}.c  — generated by UCP UI Designer
#include "ui.h"

void ui_${screen}_screen_init(void) {
    ui_${screen} = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_${screen}, LV_OBJ_FLAG_SCROLLABLE);

    ui_Title = lv_label_create(ui_${screen});
    lv_label_set_text(ui_Title, "Dryer 60\\u00B0C");
    lv_obj_align(ui_Title, LV_ALIGN_TOP_MID, 0, 10);

    ui_Arc = lv_arc_create(ui_${screen});
    lv_obj_set_size(ui_Arc, 120, 120);
    lv_arc_set_value(ui_Arc, 60);
    lv_obj_align(ui_Arc, LV_ALIGN_CENTER, 0, 0);

    ui_Start = lv_btn_create(ui_${screen});
    lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_CLICKED, NULL);
}`;
  return <CodeShell mod={MODULE_INDEX["lvgl"]} code={code} controls={
    <><span className="muted">Screen:</span>
      <select value={screen} onChange={(e) => setScreen(e.target.value)}>{["main", "settings", "graph"].map((s) => <option key={s}>{s}</option>)}</select>
    </>
  } />;
}

export function ArduinoExportView() {
  const [target, setTarget] = useState<"arduino" | "espidf">("arduino");
  const code = target === "arduino"
    ? `// sketch.ino — generated by UCP
#include <Arduino.h>
#define LED_PIN  5
#define BAUD     115200

void setup() {
  Serial.begin(BAUD);
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(500);
  digitalWrite(LED_PIN, LOW);
  delay(500);
}`
    : `// main.c — generated by UCP (ESP-IDF)
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#define LED_PIN  5

void app_main(void) {
  gpio_set_direction(LED_PIN, GPIO_MODE_OUTPUT);
  while (1) {
    gpio_set_level(LED_PIN, 1);
    vTaskDelay(pdMS_TO_TICKS(500));
    gpio_set_level(LED_PIN, 0);
    vTaskDelay(pdMS_TO_TICKS(500));
  }
}`;
  return <CodeShell mod={MODULE_INDEX["arduino"]} code={code} controls={
    <><span className="muted">Target:</span>
      <button className={`btn${target === "arduino" ? " primary" : ""}`} onClick={() => setTarget("arduino")}>Arduino</button>
      <button className={`btn${target === "espidf" ? " primary" : ""}`} onClick={() => setTarget("espidf")}>ESP-IDF</button>
    </>
  } />;
}

export function ProtoCodeGenView() {
  const [lang, setLang] = useState<"c" | "py">("c");
  const code = lang === "c"
    ? `// proto_parse.c — generated by UCP Protocol Code Gen
typedef struct { uint8_t header, cmd; uint16_t length, crc; } frame_t;

bool frame_parse(const uint8_t *buf, size_t n, frame_t *out) {
    if (n < 6 || buf[0] != 0xAA) return false;
    out->header = buf[0];
    out->cmd    = buf[1];
    out->length = (buf[2] << 8) | buf[3];
    out->crc    = (buf[4] << 8) | buf[5];
    return crc16_ccitt(buf, 4) == out->crc;
}`
    : `# proto_parse.py — generated by UCP Protocol Code Gen
import struct

def frame_parse(buf: bytes):
    if len(buf) < 6 or buf[0] != 0xAA:
        return None
    header, cmd, length, crc = struct.unpack(">BBHH", buf[:6])
    if crc16_ccitt(buf[:4]) != crc:
        return None
    return dict(header=header, cmd=cmd, length=length, crc=crc)`;
  return <CodeShell mod={MODULE_INDEX["protocodegen"]} code={code} controls={
    <><span className="muted">Language:</span>
      <button className={`btn${lang === "c" ? " primary" : ""}`} onClick={() => setLang("c")}>C</button>
      <button className={`btn${lang === "py" ? " primary" : ""}`} onClick={() => setLang("py")}>Python</button>
    </>
  } />;
}
